function(netft_enable_sanitizers target)
  if(NETFT_SANITIZERS)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
      target_compile_options(${target} PRIVATE -fno-omit-frame-pointer -fsanitize=address,undefined)
      target_link_options(${target} PRIVATE -fsanitize=address,undefined)
    else()
      message(FATAL_ERROR "NETFT_SANITIZERS requires a Clang or GNU-compatible compiler")
    endif()
  endif()
endfunction()
